### ISSUE TITLE
db connection test request!

### ISSUE THREAD

**Issue by soomni** [kimseonjeong/stdbook_1#1]
please test dbtest.java file for db connection test!!

**Comment by kimseonjeong** [comment]
db load success!!!!
그런데...
java.sql.SQLRecoverableException: IO 예외 상황: The Network Adapter could not establish the connection
이런 오류가 남 ㅠㅜㅠㅜㅠ

**Comment by soomni** [comment]
http://blog.naver.com/hodolbak/220467387806 여기 링크보고 오라클 설치 부터 한번 해봐용~~ :)

**Comment by byul9984** [comment]
서버 컴 방화벽도 다 풀어놨음!!
