### ISSUE TITLE
oracle 새로운 에러

### ISSUE THREAD

**Issue by byul9984** [kimseonjeong/stdbook_1#4]
java.sql.SQLException: ORA-01045: user DB01 lacks CREATE SESSION privilege; logon denied
혹시 이거 뜨는 분 계시나요?ㅠㅠ

**Comment by byul9984** [comment]
권한을 부여하지 않아서 생기는 에러라네요! 서버컴에서 권한 설정해야할듯!

**Comment by JiyeonYong** [comment]
#5 에 해결방법 적어뒀어요!
