### ISSUE TITLE
Change HOST of tnsnames.ora file

### ISSUE THREAD

**Issue by JiyeonYong** [kimseonjeong/stdbook_1#5]
/*
ORCL =
  (DESCRIPTION =
    (ADDRESS = (PROTOCOL = TCP)(HOST = localhost)(PORT = 1521))
    (CONNECT_DATA =
      (SERVER = DEDICATED)
      (SERVICE_NAME = orcl)
    )
  )
*/

// into

ORCL =
  (DESCRIPTION =
    (ADDRESS = (PROTOCOL = TCP)(HOST = 203.153.146.157)(PORT = 1521))
    (CONNECT_DATA =
      (SERVER = DEDICATED)
      (SERVICE_NAME = orcl)
    )
  )

//and change url of dbtest.java
//url= "jdbc:oracle:thin:@203.153.146.157:1521:orcl";

**Comment by soomni** [comment]
굿굿
